// Generated by CodiumAI
import { isNullUndefinedOrEmpty } from '@core/service/common/common'; 
describe('isNullUndefinedOrEmpty', () => {

  it('should return true when value is null', () => {
    expect(isNullUndefinedOrEmpty(null)).toBe(true);
  });

  it('should return true when value is undefined', () => {
    expect(isNullUndefinedOrEmpty(undefined)).toBe(true);
  });

  it('should return true when value is an empty string', () => {
    expect(isNullUndefinedOrEmpty("")).toBe(true);
  });

  it('should return false when value is the string "null"', () => {
    expect(isNullUndefinedOrEmpty("null")).toBe(false);
  });

  it('should return false when value is the string "undefined"', () => {
    expect(isNullUndefinedOrEmpty("undefined")).toBe(false);
  });

  it('should return false when value is a valid string with length > 0', () => {
    expect(isNullUndefinedOrEmpty("some string")).toBe(false);
  });


});
